### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by michaelcodecany** [Markkop/nft-marketplace#7]
Demo not working

**Comment by Markkop** [comment]
It's working for me. Are you using Metamask?
![image](https://user-images.githubusercontent.com/16388408/188210575-2a1df114-6a87-4463-a9d0-43b822a17071.png)

**Comment by michaelcodecany** [comment]
Thank you for your quick reply. Yes I am using Metamask.

**Comment by michaelcodecany** [comment]
Maybe I did a mistake in this part:

Make sure to use Localhost 8545 as the Metamask's network
Make sure to import local Account #0 and #1 into Metamask accounts.

So what is the setup in metamask, I did:
Network Name: Polygone
New RPC URL: http://localhost:8545
Chain ID: 31337

-------------------------------

How do you import  local Account #0 and #1 into Metamask accounts ?

Thank you

**Comment by michaelcodecany** [comment]
I have this error:

TypeError: Cannot read properties of undefined (reading 'length')

TypeError: Cannot read properties of undefined (reading 'length')
    at $ (_app-6ada3f3c52bbbcaf.js:74:236987)
    at Ie.encode (_app-6ada3f3c52bbbcaf.js:74:242724)
    at _app-6ada3f3c52bbbcaf.js:74:238863
    at Array.forEach (<anonymous>)
    at se (_app-6ada3f3c52bbbcaf.js:74:238804)
    at be.encode (_app-6ada3f3c52bbbcaf.js:74:243270)
    at Ve.encode (_app-6ada3f3c52bbbcaf.js:74:258056)
    at rt._encodeParams (_app-6ada3f3c52bbbcaf.js:74:261843)
    at rt.encodeFunctionData (_app-6ada3f3c52bbbcaf.js:74:262729)
    at _app-6ada3f3c52bbbcaf.js:74:314433

**Comment by Irfanahmedkhan** [comment]
> 

i faced the same erorr in DEMO website..
